package com.kodilla.good.patterns.food2door;

public enum Product {

    ORGANIC_GOJI_BERRIES,
    ORGANIC_BLACK_MACA_POWDER,
    BEETROOT_POWDER,
    ORGANIC_SHELLED_HEMP_SEEDS,
    ORGANIC_GRANOVITA_HEMP_OIL,
    GLUTEN_FREE_BROWN_BREAD_FLOUR,
    GLUTEN_FREE_BAKING_POWER,
    GLUTEN_FREE_ALARA_LUXURIOUS_PORRIDGE

    }
